### ISSUE TITLE
`namedtuple` deprecated argument in Python 3.7.

### ISSUE THREAD

**Issue by castillohair** [taborlab/FlowCal#301]
Running FlowCal 1.2.0 with the most recent Anaconda 2018.12, which uses Python 3.7, results in the following error:

```
Reading experiment.xlsx...

Processing Beads table (1 entries)
==================================

Beads ID B0001...
Loading file "FCFiles/Beads006.fcs"...
Performing data transformation...
Performing gating...
Plotting density plot and histogram...
Calculating standard curve for channel FL1...
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Anaconda3\lib\site-packages\flowcal-1.2.0-py3.7.egg\FlowCal\excel_ui.py", line 1671, in <module>
  File "C:\Users\user\Anaconda3\lib\site-packages\flowcal-1.2.0-py3.7.egg\FlowCal\excel_ui.py", line 1668, in run_command_line
  File "C:\Users\user\Anaconda3\lib\site-packages\flowcal-1.2.0-py3.7.egg\FlowCal\excel_ui.py", line 1550, in run
  File "C:\Users\user\Anaconda3\lib\site-packages\flowcal-1.2.0-py3.7.egg\FlowCal\excel_ui.py", line 551, in process_beads_table
  File "C:\Users\user\Anaconda3\lib\site-packages\flowcal-1.2.0-py3.7.egg\FlowCal\mef.py", line 1211, in get_transform_fxn
TypeError: namedtuple() got an unexpected keyword argument 'verbose'
```

The error can be reproduced in a non-Anaconda python 3.7 installation.

The problem seems to be the `verbose` argument in the construction of a `namedtuple`, which [has been removed in Python 3.7](https://docs.python.org/3.7/library/collections.html#collections.namedtuple). This is the offending line in `mef.py`:

```python
        MEFOutput = collections.namedtuple('MEFOutput', fields, verbose=False)
```

The easy solution is to remove the `verbose` argument. The default in previous versions was to `False` anyway, as [the documentation indicates](https://docs.python.org/3.6/library/collections.html#collections.namedtuple).

Fixing this makes FlowCal 1.2.0 work in Python 3.7.
