### ISSUE TITLE
TypeError thrown when running excel_ui.py

### ISSUE THREAD

**Issue by felixekn** [taborlab/FlowCal#310]
Conda3.7 version:  4.7.10
Matplotlib version: 3.1.0

Error report:
--------------------------------------------

> Last login: Fri Aug  2 12:55:26 on ttys001
> /Applications/Flowcal_my_develop/FlowCal/Run\ FlowCal\ \(OSX\) ; exit;
> felixs-mbp:~ felixekness$ /Applications/Flowcal_my_develop/FlowCal/Run\ FlowCal\ \(OSX\) ; exit;
> //anaconda3/lib/python3.7/runpy.py:125: RuntimeWarning: 'FlowCal.excel_ui' found in sys.modules after import of package 'FlowCal', but prior to execution of 'FlowCal.excel_ui'; this may result in unpredictable behaviour
>   warn(RuntimeWarning(msg))
> objc[9329]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9fc6d3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1c1dcbdf50). One of the two will be used. Which one is undefined.
> Reading experiment.xlsx...
> 
> Processing Beads table (1 entries)
> ==================================
> 
> Beads ID B0001...
> Loading file "FCFiles/Beads006.fcs"...
> Performing data transformation...
> Performing gating...
> Plotting density plot and histogram...
> Traceback (most recent call last):
>   File "//anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "//anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Applications/Flowcal_my_develop/FlowCal/FlowCal/excel_ui.py", line 1671, in <module>
>     run_command_line()
>   File "/Applications/Flowcal_my_develop/FlowCal/FlowCal/excel_ui.py", line 1668, in run_command_line
>     hist_sheet=args.histogram_sheet)
>   File "/Applications/Flowcal_my_develop/FlowCal/FlowCal/excel_ui.py", line 1550, in run
>     full_output=True)
>   File "/Applications/Flowcal_my_develop/FlowCal/FlowCal/excel_ui.py", line 487, in process_beads_table
>     savefig=figname)
>   File "/Applications/Flowcal_my_develop/FlowCal/FlowCal/plot.py", line 1716, in density_and_hist
>     density2d(data, channels=density_channels, **density_params)
>   File "/Applications/Flowcal_my_develop/FlowCal/FlowCal/plot.py", line 1211, in density2d
>     plt.gca().set_xscale(xscale, data=data_plot, channel=0)
>   File "//anaconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 3322, in set_xscale
>     ax.xaxis._set_scale(value, **kwargs)
>   File "//anaconda3/lib/python3.7/site-packages/matplotlib/axis.py", line 799, in _set_scale
>     self._scale = mscale.scale_factory(value, self, **kwargs)
>   File "//anaconda3/lib/python3.7/site-packages/matplotlib/scale.py", line 743, in scale_factory
>     return _scale_mapping[scale](axis, **kwargs)
>   File "/Applications/Flowcal_my_develop/FlowCal/FlowCal/plot.py", line 677, in __init__
>     matplotlib.scale.ScaleBase.__init__(self)
> TypeError: __init__() missing 1 required positional argument: 'axis'
> Press [Enter] to finish...

**Comment by felixekn** [comment]
Identified reason for error:

In plot.py, the `_LogicleScale()` class fails at `__init__(self, axis, **kwargs)`. As of Matplotlib 3.1.0, `matplotlib.scale.ScaleBase__init__(self)` requires a `matplotlib.axis.Axis` object as a second argument.

**Comment by castillohair** [comment]
The obvious solution would be to modify [this line](https://github.com/taborlab/FlowCal/blob/develop/FlowCal/plot.py#L677), which has the following contents:

```python
    def __init__(self, axis, **kwargs):
        # Run parent's constructor
        matplotlib.scale.ScaleBase.__init__(self)
```

to the following:

```python
    def __init__(self, axis, **kwargs):
        # Run parent's constructor
        matplotlib.scale.ScaleBase.__init__(self, axis)
```

While this seems to work with matplotlib 3.1.0 and greater, it breaks compatibility with any previous version, including 3.0.x. Therefore, the recommended solution to preserve some level of compatibility is the following:

```python
    def __init__(self, axis, **kwargs):
        # Run parent's constructor
        if packaging.version.parse(matplotlib.__version__) \
                >= packaging.version.parse('3.1.0'):
            matplotlib.scale.ScaleBase.__init__(self, axis)
        else:
            matplotlib.scale.ScaleBase.__init__(self)
```

I'll submit a PR with this code.
